### ISSUE TITLE
compile with ndk error

### ISSUE THREAD

**Issue by KORuL** [darrenldl/reed-solomon-erasure#28] opened 2018-10-28 11:42 UTC
I try to build using ndk dll library for android with next  cargo-config/toml :

```
[target.aarch64-linux-android]
ar = "/home/user/project/NDK/arm64/bin/aarch64-linux-android-ar"
linker = "/home/user/project/NDK/arm64/bin/aarch64-linux-android-clang"

[target.armv7-linux-androideabi]
ar = "/home/user/project/NDK/arm/bin/arm-linux-androideabi-ar"
linker = "/home/user/project/NDK/arm/bin/arm-linux-androideabi-clang"

[target.i686-linux-android]
ar = "/home/user/project/NDK/x86/bin/i686-linux-android-ar"
linker = "/home/user/project/NDK/x86/bin/i686-linux-android-clang"
```

and build with command:

```
cargo build --target aarch64-linux-android --release
cargo build --target arm-linux-androideabi --release
cargo build --target i686-linux-android --release
```

, but your library causes the following error:

```
error: failed to run custom build command for `reed-solomon-erasure v3.1.1`                                                                
process didn't exit successfully: `/home/user/project/hydrabadger-android/target/release/build/reed-solomon-erasure-1b09dd6802a14405/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("arm-linux-androideabi")
TARGET = Some("arm-linux-androideabi")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("arm-linux-androideabi")
TARGET = Some("arm-linux-androideabi")
HOST = Some("x86_64-unknown-linux-gnu")
CC_arm-linux-androideabi = None
CC_arm_linux_androideabi = None
TARGET_CC = None
CC = None
TARGET = Some("arm-linux-androideabi")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_arm-linux-androideabi = None
CFLAGS_arm_linux_androideabi = None
TARGET_CFLAGS = None
CFLAGS = None
DEBUG = Some("false")
TARGET = Some("arm-linux-androideabi")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_arm-linux-androideabi = None
CFLAGS_arm_linux_androideabi = None
TARGET_CFLAGS = None
CFLAGS = None
TARGET = Some("arm-linux-androideabi")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_arm-linux-androideabi = None
CFLAGS_arm_linux_androideabi = None
TARGET_CFLAGS = None
CFLAGS = None
running: "arm-linux-androideabi-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-Wall" "-Wextra" "-o" "/home/user/project/hydrabadger-android/target/arm-linux-androideabi/release/build/reed-solomon-erasure-1674c464fde2b8a2/out/simd_c/reedsolomon.o" "-c" "simd_c/reedsolomon.c"
cargo:warning=simd_c/reedsolomon.c:243:43: error: argument to '__builtin_neon_vshrq_n_v' must be a constant integer
cargo:warning=        const v128 result = { .uint8x16 = vshrq_n_u8(in.uint8x16, n) };
cargo:warning=                                          ^                       ~
cargo:warning=/home/user/project/NDK/arm/lib64/clang/7.0.2/include/arm_neon.h:23381:24: note: expanded from macro 'vshrq_n_u8'
cargo:warning=  __ret = (uint8x16_t) __builtin_neon_vshrq_n_v((int8x16_t)__s0, __p1, 48); \
cargo:warning=                       ^                                         ~~~~
cargo:warning=1 error generated.
exit code: 1

--- stderr
clang70: error: no input files
thread 'main' panicked at '

Internal error occurred: Command "arm-linux-androideabi-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-Wall" "-Wextra" "-o" "/home/user/project/hydrabadger-android/target/arm-linux-androideabi/release/build/reed-solomon-erasure-1674c464fde2b8a2/out/simd_c/reedsolomon.o" "-c" "simd_c/reedsolomon.c" with args "arm-linux-androideabi-gcc" did not execute successfully (status code exit code: 1).

', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.23/src/lib.rs:2253:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...

```

And please merge the dev branch with master

**Comment by KORuL** [comment] 2018-10-28 12:57
I use 3.1.1, this error on 3.1.1

**Comment by darrenldl** [comment] 2018-10-28 13:38
Oh sorry, I read the last PR again and the fix wouldn't work for this issue.

I'm fixing it right now, should be done in a few minutes

**Comment by darrenldl** [comment] 2018-10-28 13:51
Hello @KORuL 

The issue is tracked at PR #30 

I will be off to bed now, but I will check for replies in the morning.

Let me know if the dev branch works for you, if so then I'll publish it to crates.io

**Comment by KORuL** [comment] 2018-10-28 17:48
```
error: failed to run custom build command for `reed-solomon-erasure v3.1.2 (https://github.com/darrenldl/reed-solomon-erasure?branch=dev#668ea466)` 
process didn't exit successfully: `/home/user/project/hydrabadger-android/target/release/build/reed-solomon-erasure-4b04d78cb7ff7758/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("aarch64-linux-android")
TARGET = Some("aarch64-linux-android")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("aarch64-linux-android")
TARGET = Some("aarch64-linux-android")
HOST = Some("x86_64-unknown-linux-gnu")
CC_aarch64-linux-android = None
CC_aarch64_linux_android = None
TARGET_CC = None
CC = None
TARGET = Some("aarch64-linux-android")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_aarch64-linux-android = None
CFLAGS_aarch64_linux_android = None
TARGET_CFLAGS = None
CFLAGS = None
DEBUG = Some("false")
TARGET = Some("aarch64-linux-android")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_aarch64-linux-android = None
CFLAGS_aarch64_linux_android = None
TARGET_CFLAGS = None
CFLAGS = None
TARGET = Some("aarch64-linux-android")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_aarch64-linux-android = None
CFLAGS_aarch64_linux_android = None
TARGET_CFLAGS = None
CFLAGS = None
running: "aarch64-linux-android-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-Wall" "-Wextra" "-std=c11" "-o" "/home/user/project/hydrabadger-android/target/aarch64-linux-android/release/build/reed-solomon-erasure-fa349c493823480d/out/simd_c/reedsolomon.o" "-c" "simd_c/reedsolomon.c"
cargo:warning=simd_c/reedsolomon.c:243:43: error: argument to '__builtin_neon_vshrq_n_v' must be a constant integer
cargo:warning=        const v128 result = { .uint8x16 = vshrq_n_u8(in.uint8x16, n) };
cargo:warning=                                          ^                       ~
cargo:warning=/home/user/project/NDK/arm64/lib64/clang/7.0.2/include/arm_neon.h:23381:24: note: expanded from macro 'vshrq_n_u8'
cargo:warning=  __ret = (uint8x16_t) __builtin_neon_vshrq_n_v((int8x16_t)__s0, __p1, 48); \
cargo:warning=                       ^                                         ~~~~
cargo:warning=1 error generated.
exit code: 1

--- stderr
clang70: error: no input files
thread 'main' panicked at '

Internal error occurred: Command "aarch64-linux-android-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-Wall" "-Wextra" "-std=c11" "-o" "/home/user/project/hydrabadger-android/target/aarch64-linux-android/release/build/reed-solomon-erasure-fa349c493823480d/out/simd_c/reedsolomon.o" "-c" "simd_c/reedsolomon.c" with args "aarch64-linux-android-gcc" did not execute successfully (status code exit code: 1).

', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.23/src/lib.rs:2253:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed                                             
```

**Comment by darrenldl** [comment] 2018-10-28 23:09
So I made another mistake in the conditional compilation, which is fixed in the dev branch now.

Let me know if the dev branch now works on your targets

**Comment by KORuL** [comment] 2018-10-29 17:47
```
error: failed to run custom build command for `reed-solomon-erasure v3.1.2 (https://github.com/darrenldl/reed-solomon-erasure?branch=dev#2d68b9d6)` 
process didn't exit successfully: `/home/user/project/hydrabadger-android/target/release/build/reed-solomon-erasure-4b04d78cb7ff7758/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("aarch64-linux-android")
TARGET = Some("aarch64-linux-android")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("aarch64-linux-android")
TARGET = Some("aarch64-linux-android")
HOST = Some("x86_64-unknown-linux-gnu")
CC_aarch64-linux-android = None
CC_aarch64_linux_android = None
TARGET_CC = None
CC = None
TARGET = Some("aarch64-linux-android")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_aarch64-linux-android = None
CFLAGS_aarch64_linux_android = None
TARGET_CFLAGS = None
CFLAGS = None
DEBUG = Some("false")
TARGET = Some("aarch64-linux-android")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_aarch64-linux-android = None
CFLAGS_aarch64_linux_android = None
TARGET_CFLAGS = None
CFLAGS = None
TARGET = Some("aarch64-linux-android")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_aarch64-linux-android = None
CFLAGS_aarch64_linux_android = None
TARGET_CFLAGS = None
CFLAGS = None
running: "aarch64-linux-android-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-Wall" "-Wextra" "-std=c11" "-o" "/home/user/project/hydrabadger-android/target/aarch64-linux-android/release/build/reed-solomon-erasure-fa349c493823480d/out/simd_c/reedsolomon.o" "-c" "simd_c/reedsolomon.c"
cargo:warning=simd_c/reedsolomon.c:243:43: error: argument to '__builtin_neon_vshrq_n_v' must be a constant integer
cargo:warning=        const v128 result = { .uint8x16 = vshrq_n_u8(in.uint8x16, n) };
cargo:warning=                                          ^                       ~
cargo:warning=/home/user/project/NDK/arm64/lib64/clang/7.0.2/include/arm_neon.h:23381:24: note: expanded from macro 'vshrq_n_u8'
cargo:warning=  __ret = (uint8x16_t) __builtin_neon_vshrq_n_v((int8x16_t)__s0, __p1, 48); \
cargo:warning=                       ^                                         ~~~~
cargo:warning=1 error generated.
exit code: 1

--- stderr
clang70: error: no input files
thread 'main' panicked at '

Internal error occurred: Command "aarch64-linux-android-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-Wall" "-Wextra" "-std=c11" "-o" "/home/user/project/hydrabadger-android/target/aarch64-linux-android/release/build/reed-solomon-erasure-fa349c493823480d/out/simd_c/reedsolomon.o" "-c" "simd_c/reedsolomon.c" with args "aarch64-linux-android-gcc" did not execute successfully (status code exit code: 1).

', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.23/src/lib.rs:2253:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed        
```

**Comment by KORuL** [comment] 2018-10-29 18:39
I accidentally discovered here that reed-solomon-erasure = {version = "3.1", features = ["pure-rust"]} compiles to all three target android perfectly

**Comment by darrenldl** [comment] 2018-10-29 22:58
Okay I kept making mistakes, sorry about it.

And yep, "pure-rust" feature disables SIMD always, so that is a backup plan in case the automatic detection does not work well.

Sorry again for keep messing it up. I need to submit my paper to a conference in 3 weeks, and can't really focus on other projects too well.

=====

I am really lost on how to detect if the target is Android at this point, I have posted a question on the rust forum [here](https://users.rust-lang.org/t/target-triple-and-conditional-compilation-for-android/21772).

If you know the answer, please leave it here or there as well. Greatly appreciated.

**Comment by darrenldl** [comment] 2018-11-10 09:08
Didn't seem to see any new solutions, so I will close this issue for now.

Feel free to open another issue if you have new issues or you have a solution to this problem.

**Closed by darrenldl** 2018-11-10 09:08 UTC
